clang-tidy: Remove unused lambda captures
The following errors were reported during clang-tidy enablement due
to unused lambda captures.

'''
../src/metric.cpp:119:50: error: lambda capture 'this' is not used [-Werror
'''

The fix involves removing these unused lambda captures.

Tested: Build and unit testing verified.

Change-Id: I6a4b42ea3df7513e1208638f427007680e2a15cf
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>