clang-tidy: Suppress unused lambda captures
The following errors were reported during clang-tidy enablement due to
unused lambda captures. This temporary fix suppresses the warnings using
pragma diagnostic ignore checks until a permanent solution is implemented.

Changes:
- Added pragma directives to suppress the -Wunused-lambda-capture warning
  in specific code sections.

'''
../src/metric.cpp:119:50: error: lambda capture 'this' is not used [-Werror
'''

Tested: Build and unit testing verified.

Change-Id: I6a4b42ea3df7513e1208638f427007680e2a15cf
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>